// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for footer documents */
type FooterDocumentData = Record<string, never>;
/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<FooterDocumentData>, "footer", Lang>;
/** Content for homepage documents */
interface HomepageDocumentData {
    /**
     * Slice Zone field in *homepage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageDocumentDataSlicesSlice>;
}
/**
 * Slice for *homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlicesSlice = HomepageSlice | SlliderSlice | OrdersSlice;
/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageDocumentData>, "homepage", Lang>;
/** Content for navigation documents */
interface NavigationDocumentData {
    /**
     * menu field in *navigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.menu[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/group
     *
     */
    menu: prismicT.GroupField<Simplify<NavigationDocumentDataMenuItem>>;
    /**
     * Slice Zone field in *navigation*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<NavigationDocumentDataSlicesSlice>;
}
/**
 * Item in navigation → menu
 *
 */
export interface NavigationDocumentDataMenuItem {
    /**
     * menus field in *navigation → menu*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.menu[].menus
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    menus: prismicT.RichTextField;
    /**
     * links field in *navigation → menu*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.menu[].links
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    links: prismicT.LinkField;
}
/**
 * Slice for *navigation → Slice Zone*
 *
 */
type NavigationDocumentDataSlicesSlice = never;
/**
 * navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<NavigationDocumentData>, "navigation", Lang>;
/** Content for settings documents */
interface SettingsDocumentData {
    /**
     * logo field in *settings*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: settings.logo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    logo: prismicT.RichTextField;
    /**
     * name field in *settings*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: settings.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    name: prismicT.RichTextField;
    /**
     * Slice Zone field in *settings*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: settings.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<SettingsDocumentDataSlicesSlice>;
}
/**
 * Slice for *settings → Slice Zone*
 *
 */
type SettingsDocumentDataSlicesSlice = never;
/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<SettingsDocumentData>, "settings", Lang>;
export type AllDocumentTypes = FooterDocument | HomepageDocument | NavigationDocument | SettingsDocument;
/**
 * Primary content in Footer → Primary
 *
 */
interface FooterSliceDefaultPrimary {
    /**
     * Title field in *Footer → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: footer.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *Footer → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: footer.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Footer`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FooterSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Footer*
 *
 */
type FooterSliceVariation = FooterSliceDefault;
/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: `Footer`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FooterSlice = prismicT.SharedSlice<"footer", FooterSliceVariation>;
/**
 * Primary content in Herosection → Primary
 *
 */
interface HomepageSliceDefaultPrimary {
    /**
     * title field in *Herosection → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * img field in *Herosection → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.primary.img
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    img: prismicT.ImageField<never>;
}
/**
 * Item in Herosection → Items
 *
 */
export interface HomepageSliceDefaultItem {
    /**
     * img field in *Herosection → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.items[].img
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    img: prismicT.ImageField<never>;
    /**
     * tittle field in *Herosection → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.items[].tittle
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    tittle: prismicT.RichTextField;
    /**
     * description field in *Herosection → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage.items[].description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for Herosection Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Homepage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomepageSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HomepageSliceDefaultPrimary>, Simplify<HomepageSliceDefaultItem>>;
/**
 * Slice variation for *Herosection*
 *
 */
type HomepageSliceVariation = HomepageSliceDefault;
/**
 * Herosection Shared Slice
 *
 * - **API ID**: `homepage`
 * - **Description**: `Homepage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomepageSlice = prismicT.SharedSlice<"homepage", HomepageSliceVariation>;
/**
 * Primary content in Orders → Primary
 *
 */
interface OrdersSliceDefaultPrimary {
    /**
     * Title field in *Orders → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: orders.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Item in Orders → Items
 *
 */
export interface OrdersSliceDefaultItem {
    /**
     * img field in *Orders → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: orders.items[].img
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    img: prismicT.ImageField<never>;
}
/**
 * Default variation for Orders Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Orders`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type OrdersSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<OrdersSliceDefaultPrimary>, Simplify<OrdersSliceDefaultItem>>;
/**
 * Slice variation for *Orders*
 *
 */
type OrdersSliceVariation = OrdersSliceDefault;
/**
 * Orders Shared Slice
 *
 * - **API ID**: `orders`
 * - **Description**: `Orders`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type OrdersSlice = prismicT.SharedSlice<"orders", OrdersSliceVariation>;
/**
 * Item in Sllider → Items
 *
 */
export interface SlliderSliceDefaultItem {
    /**
     * img field in *Sllider → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: sllider.items[].img
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    img: prismicT.ImageField<never>;
}
/**
 * Default variation for Sllider Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Sllider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SlliderSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, Simplify<SlliderSliceDefaultItem>>;
/**
 * orders variation for Sllider Slice
 *
 * - **API ID**: `orders`
 * - **Description**: `Sllider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SlliderSliceOrders = prismicT.SharedSliceVariation<"orders", Record<string, never>, never>;
/**
 * Slice variation for *Sllider*
 *
 */
type SlliderSliceVariation = SlliderSliceDefault | SlliderSliceOrders;
/**
 * Sllider Shared Slice
 *
 * - **API ID**: `sllider`
 * - **Description**: `Sllider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type SlliderSlice = prismicT.SharedSlice<"sllider", SlliderSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { FooterDocumentData, FooterDocument, HomepageDocumentData, HomepageDocumentDataSlicesSlice, HomepageDocument, NavigationDocumentData, NavigationDocumentDataMenuItem, NavigationDocumentDataSlicesSlice, NavigationDocument, SettingsDocumentData, SettingsDocumentDataSlicesSlice, SettingsDocument, AllDocumentTypes, FooterSliceDefaultPrimary, FooterSliceDefault, FooterSliceVariation, FooterSlice, HomepageSliceDefaultPrimary, HomepageSliceDefaultItem, HomepageSliceDefault, HomepageSliceVariation, HomepageSlice, OrdersSliceDefaultPrimary, OrdersSliceDefaultItem, OrdersSliceDefault, OrdersSliceVariation, OrdersSlice, SlliderSliceDefaultItem, SlliderSliceDefault, SlliderSliceOrders, SlliderSliceVariation, SlliderSlice };
    }
}
