// Code generated by Slice Machine. DO NOT EDIT.

import Herosection from './Herosection';
import Orders from './Orders';
import Sllider from './Sllider';

export {
	Herosection,
	Orders,
	Sllider,
};

export const components = {
	homepage: Herosection,
	orders: Orders,
	sllider: Sllider,
};
